// <auto-generated />
using System;
using GeoTrack.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoTrack.API.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20260201120000_AddTenantIdToGpsFixes")]
    partial class AddTenantIdToGpsFixes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoTrack.Domain.Common.ValueObjects.GpsFix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedNever()
                        .HasColumnType("uuid");

                    b.Property<double?>("accuracy_meters")
                        .HasPrecision(9, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_meters");

                    b.Property<double?>("altitude_meters")
                        .HasPrecision(9, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("altitude_meters");

                    b.Property<string>("correlation_id")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<long?>("device_sequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<DateTime>("device_time_utc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_time_utc");

                    b.Property<double?>("heading_degrees")
                        .HasPrecision(9, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("heading_degrees");

                    b.Property<double>("latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double?>("odometer_km")
                        .HasPrecision(14, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("odometer_km");

                    b.Property<int>("quality")
                        .HasColumnType("integer")
                        .HasColumnName("quality");

                    b.Property<DateTime>("received_at_utc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<double?>("speed_kph")
                        .HasPrecision(9, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kph");

                    b.Property<int>("source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<Guid>("tenant_id")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("vehicle_id")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("tenant_id", "vehicle_id", "device_time_utc")
                        .HasDatabaseName("ix_gpsfix_tenant_vehicle_devicetime");

                    b.ToTable("gps_fixes");
                });

            // Note: other entities are unchanged from previous snapshot and omitted here intentionally.
        }
    }
}
