﻿// <auto-generated />
using System;
using GeoTrack.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GeoTrack.API.Migrations
{
    [DbContext(typeof(TrackingDbContext))]
    [Migration("20260130163344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GeoTrack.Domain.Common.ValueObjects.GpsFix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("Accuracy")
                        .HasPrecision(9, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_meters");

                    b.Property<double?>("AltitudeMeters")
                        .HasPrecision(9, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("altitude_meters");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<long?>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<DateTime>("DeviceTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_time_utc");

                    b.Property<double?>("Heading")
                        .HasPrecision(9, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("heading_degrees");

                    b.Property<double>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<double?>("OdometerKm")
                        .HasPrecision(14, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("odometer_km");

                    b.Property<int>("Quality")
                        .HasColumnType("integer")
                        .HasColumnName("quality");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<double?>("Speed")
                        .HasPrecision(9, 3)
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kph");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.HasKey("Id");

                    b.HasIndex("ReceivedAtUtc")
                        .HasDatabaseName("ix_gpsfix_receivedat");

                    b.HasIndex("VehicleId", "DeviceTimeUtc")
                        .HasDatabaseName("ix_gpsfix_vehicle_devicetime");

                    b.ToTable("gps_fixes", (string)null);
                });

            modelBuilder.Entity("GeoTrack.Domain.Vehicles.VehicleLatestLocation", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("vehicle_id");

                    b.Property<double?>("AccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("accuracy_meters");

                    b.Property<long>("DeviceSequence")
                        .HasColumnType("bigint")
                        .HasColumnName("device_sequence");

                    b.Property<DateTime>("DeviceTimeUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("device_time_utc");

                    b.Property<Guid>("GpsFixId")
                        .HasColumnType("uuid")
                        .HasColumnName("gps_fix_id");

                    b.Property<double?>("HeadingDegrees")
                        .HasColumnType("double precision")
                        .HasColumnName("heading_degrees");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<Guid?>("RouteScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("route_schedule_id");

                    b.Property<double?>("SpeedKph")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kph");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("now()");

                    b.HasKey("TenantId", "VehicleId");

                    b.HasIndex("TenantId", "ReceivedAtUtc")
                        .HasDatabaseName("ix_vll_tenant_receivedat");

                    b.HasIndex("TenantId", "VehicleId")
                        .HasDatabaseName("ix_vll_tenant_vehicle");

                    b.ToTable("vehicle_latest_location", (string)null);
                });

            modelBuilder.Entity("GeoTrack.API.Data.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_tenants_name");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("GeoTrack.API.Data.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("TenantId", "Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_vehicles_tenant");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("GeoTrack.Domain.Vehicles.VehicleLatestLocation", b =>
                {
                    b.HasOne("GeoTrack.API.Data.Entities.Vehicle", "Vehicle")
                        .WithOne()
                        .HasForeignKey("GeoTrack.Domain.Vehicles.VehicleLatestLocation", "TenantId", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GeoTrack.API.Data.Entities.Vehicle", b =>
                {
                    b.OwnsOne("GeoTrack.API.Data.Entities.VehicleIdentity", "Identity", b1 =>
                        {
                            b1.Property<Guid>("VehicleTenantId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("ExternalId")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("external_id");

                            b1.Property<string>("Name")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("name");

                            b1.Property<string>("RegistrationNumber")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("registration_number");

                            b1.HasKey("VehicleTenantId", "VehicleId");

                            b1.HasIndex("VehicleTenantId", "RegistrationNumber")
                                .IsUnique()
                                .HasDatabaseName("ux_vehicle_tenant_registration_number")
                                .HasFilter("registration_number IS NOT NULL");

                            b1.ToTable("vehicles");

                            b1.WithOwner()
                                .HasForeignKey("VehicleTenantId", "VehicleId");
                        });

                    b.Navigation("Identity")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
