namespace GeoTrack.Domain.Common.ValueObjects
{
    /// <summary>
    /// Indicates where a telemetry point originated from.
    /// 
    /// This is used to distinguish between real device data, data relayed
    /// through infrastructure, simulated test data, and historical backfills.
    /// 
    /// It is important for:
    /// - Debugging and auditing
    /// - Trust and data quality decisions
    /// - Reprocessing and replay pipelines
    /// - Separating real-world tracking from test traffic
    /// </summary>
    public enum TelemetrySource
    {
        /// <summary>
        /// Data sent directly from a physical GPS device on the vehicle.
        /// This is considered the primary and most trustworthy source.
        /// </summary>
        Device = 1,

        /// <summary>
        /// Data forwarded by an edge gateway or intermediary
        /// (e.g., IoT hub, message broker, or relay service).
        /// Device time may be preserved but transport latency may exist.
        /// </summary>
        Gateway = 2,

        /// <summary>
        /// Data generated by a simulator for testing, QA, or demos.
        /// Should not be mixed with production analytics unless explicitly intended.
        /// </summary>
        Simulator = 3,

        /// <summary>
        /// Data inserted after the fact, typically for historical recovery,
        /// imports from other systems, or correction of missing telemetry.
        /// Often arrives out-of-order relative to live data.
        /// </summary>
        Backfill = 4
    }
}